In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold

In [ ]:
#ENAC

#5289 (training)
positive_5289 = "/content/drive/My Drive/Colab Notebooks/Pattern Recognition/5289_thaliana .npy files/Positive/A.thaliana5289_pos_ENAC_4000.npy"
negative_5289 = "/content/drive/My Drive/Colab Notebooks/Pattern Recognition/5289_thaliana .npy files/Negative/A.thaliana5289_neg_ENAC_4000.npy"

#1000 (test)
positive_1000 = "/content/drive/My Drive/Colab Notebooks/Pattern Recognition/1000_thaliana .npy files/Positive/1000_pos_ENAC.npy"
negative_1000 = "/content/drive/My Drive/Colab Notebooks/Pattern Recognition/1000_thaliana .npy files/Negative/1000_neg_ENAC.npy"

#x_training and x_testing
x_train_positive = np.load(positive_5289)
x_train_negative = np.load(negative_5289)
x_test_positive = np.load(positive_1000)
x_test_negative = np.load(negative_1000)

#y_training and y_testing
y_train_positive = np.tile(1,5289)
y_train_negative = np.tile(0,5289)
y_test_positive = np.tile(1,1000)
y_test_negative = np.tile(0,1000)


#1000 instances, 148 features
#5289 instance, 148 features

In [ ]:
#printing the content number of the npy files
print(x_test_negative.shape)
print(y_test_negative.shape)

print(x_train_negative.shape)
print(y_train_negative.shape)


(1000, 148)
(1000,)
(5289, 148)
(5289,)


In [ ]:
seed = 40
np.random.seed(seed)

In [ ]:
#split training set to training and validation
x_training_pos, x_valid_pos, y_training_pos, y_valid_pos = train_test_split(x_train_positive, y_train_positive, test_size=0.20, random_state=seed)
x_training_neg, x_valid_neg, y_training_neg, y_valid_neg = train_test_split(x_train_negative, y_train_negative, test_size=0.20, random_state=seed)

#printing the shape
print(x_training_pos.shape)
print(x_valid_pos.shape)


(4231, 148)
(1058, 148)


In [ ]:
#concatenating (linking positive and negative)

#training set
x_train_s = np.concatenate((x_training_pos, x_training_neg), axis=0)
y_train_s = np.concatenate((y_training_pos, y_training_neg))

#validation set
x_val_s = np.concatenate((x_valid_pos, x_valid_neg), axis=0)
y_val_s = np.concatenate((y_valid_pos, y_valid_neg))

#test set
x_test_s = np.concatenate((x_test_positive, x_test_negative))
y_test_s = np.concatenate((y_test_positive, y_test_negative))

#print test shape
print(x_test_s.shape)
print(y_test_s.shape)

(2000, 148)
(2000,)


In [18]:
print(x_train_s.shape)
print(y_train_s.shape)

(8462, 148)
(8462,)


In [19]:
c = 5
clf = SVC(C=c, random_state = seed)

In [20]:
clf.fit(x_train_s, y_train_s)

SVC(C=5, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=40, shrinking=True, tol=0.001,
    verbose=False)

In [21]:
y_val_pred = clf.predict(x_val_s)

In [22]:
print(y_val_pred)
print(y_val_s)

[1 1 0 ... 0 0 0]
[1 1 1 ... 0 0 0]


In [23]:
val_acc = accuracy_score(y_val_s, y_val_pred)
#check accuracy for c = n (here, n=5)
print(val_acc)

0.9560491493383743


In [25]:
y_test_pred = clf.predict(x_test_s)
test_acc = accuracy_score(y_test_s, y_test_pred)
#check test accuracy
print(test_acc)

0.616


In [26]:
y_train_pred = clf.predict(x_train_s)
train_acc = accuracy_score(y_train_s, y_train_pred)
print(train_acc)

0.9998818246277476


In [27]:
kf = KFold(n_splits=5, random_state=seed)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


In [28]:
#DNC

#5289 (training)
positive_5289 = "/content/drive/My Drive/Colab Notebooks/Pattern Recognition/5289_thaliana .npy files/Positive/A.thaliana5289_pos_DNC_4000.npy"
negative_5289 = "/content/drive/My Drive/Colab Notebooks/Pattern Recognition/5289_thaliana .npy files/Negative/A.thaliana5289_neg_DNC_4000.npy"

#1000 (test)
positive_1000 = "/content/drive/My Drive/Colab Notebooks/Pattern Recognition/1000_thaliana .npy files/Positive/1000_pos_DNC.npy"
negative_1000 = "/content/drive/My Drive/Colab Notebooks/Pattern Recognition/1000_thaliana .npy files/Negative/1000_neg_DNC.npy"

#x_training and x_testing
x_train_positive = np.load(positive_5289)
x_train_negative = np.load(negative_5289)
x_test_positive = np.load(positive_1000)
x_test_negative = np.load(negative_1000)

#y_training and y_testing
y_train_positive = np.tile(1,5289)
y_train_negative = np.tile(0,5289)
y_test_positive = np.tile(1,1000)
y_test_negative = np.tile(0,1000)


#1000 instances, 148 features
#5289 instance, 148 features

#printing the content number of the npy files
print(x_test_negative.shape)
print(y_test_negative.shape)

print(x_train_negative.shape)
print(y_train_negative.shape)

seed = 40
np.random.seed(seed)

#split training set to training and validation
x_training_pos, x_valid_pos, y_training_pos, y_valid_pos = train_test_split(x_train_positive, y_train_positive, test_size=0.20, random_state=seed)
x_training_neg, x_valid_neg, y_training_neg, y_valid_neg = train_test_split(x_train_negative, y_train_negative, test_size=0.20, random_state=seed)

#printing the shape
print(x_training_pos.shape)
print(x_valid_pos.shape)

#concatenating (linking positive and negative)

#training set
x_train_s = np.concatenate((x_training_pos, x_training_neg), axis=0)
y_train_s = np.concatenate((y_training_pos, y_training_neg))

#validation set
x_val_s = np.concatenate((x_valid_pos, x_valid_neg), axis=0)
y_val_s = np.concatenate((y_valid_pos, y_valid_neg))

#test set
x_test_s = np.concatenate((x_test_positive, x_test_negative))
y_test_s = np.concatenate((y_test_positive, y_test_negative))

#print test shape
print(x_test_s.shape)
print(y_test_s.shape)

print(x_train_s.shape)
print(y_train_s.shape)


(1000, 16)
(1000,)
(5289, 16)
(5289,)
(4231, 16)
(1058, 16)
(2000, 16)
(2000,)
(8462, 16)
(8462,)


In [29]:
c = 5
clf = SVC(C=c, random_state = seed)

In [30]:
clf.fit(x_train_s, y_train_s)

y_val_pred = clf.predict(x_val_s)
print(y_val_pred)
print(y_val_s)

val_acc = accuracy_score(y_val_s, y_val_pred)
#check accuracy for c = n (here, n=5)
print(val_acc)

y_test_pred = clf.predict(x_test_s)
test_acc = accuracy_score(y_test_s, y_test_pred)
#check test accuracy
print(test_acc)

y_train_pred = clf.predict(x_train_s)
train_acc = accuracy_score(y_train_s, y_train_pred)
print(train_acc)

[1 1 1 ... 0 0 0]
[1 1 1 ... 0 0 0]
0.9933837429111532
0.9005
0.9994091231387379


In [31]:
kf = KFold(n_splits=5, random_state=seed)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
